### ISSUE TITLE
Update some external commands

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak-doc#36]
Some external commands seems not up to date are missing some hint:

1. [ACKNOWLEDGE_HOST_PROBLEM](https://github.com/Alignak-monitoring/alignak-doc/blob/develop/source/20_annexes/external_commands_list.rst#acknowledge_host_problem)

  * Code section (`ACKNOWLEDGE_HOST_PROBLEM;<host_name>;<sticky>;...`) seems broken.
  * Sticky, notify and persistent need other value (e.g.: if sticky not set to 2, what is the other value ?)

2. [ACKNOWLEDGE_SVC_PROBLEM](https://github.com/Alignak-monitoring/alignak-doc/blob/develop/source/20_annexes/external_commands_list.rst#acknowledge_svc_problem)

  * This command must provide the name of the service and not its description
  * Sticky, notify and persistent need other value (as in ACKNOWLEDGE_HOST_PROBLEM)

3. [SCHEDULE_HOST_DOWNTIME](https://github.com/Alignak-monitoring/alignak-doc/blob/develop/source/20_annexes/external_commands_list.rst#schedule_host_downtime) and [SCHEDULE_SVC_DOWNTIME](https://github.com/Alignak-monitoring/alignak-doc/blob/develop/source/20_annexes/external_commands_list.rst#schedule_svc_downtime)

This commands needs same change than for Acknowledge: name of service instead of service description.

I did not check the other commands, but there seems to be others where `service_description` needs to be changed.

**Comment by mohierf** [comment]
Thanks @algorys : which doc branch did you checked ? The most up-to-date is: http://docs.alignak.net/en/develop-environment/ ... which is the last one I updated for the new Alignak version.

1. I will update to add information about the allwoed fields values
2. `service_description` is the name of the field that is commonly used by Nagios and  al. ... this is why it is used in place of the service `name`. As of it, no change is needed IMHO 😉

**Comment by algorys** [comment]
@mohierf the develop branch but develop+env seems the same for these problems.

1. Ok
2. I understand well. I'm not Nagios expert and so for people who do not necessarily know Nagios, it's not easy to understand.

Another idea is to have some examples and informations about endpoint to use (`command`) or maybe add a link to [external-command](http://alignak-module-ws.readthedocs.io/en/develop/04_services/07-external-command.html) at start of annexe ?
